---
- name: Change hostname
  hostname:
    name: "{{ inventory_hostname }}"
#-------------------------------------------------------------#
- name: Set timezone to Europe/Warsaw
  timezone:
    name: Europe/Warsaw
#-------------------------------------------------------------#