---
- name: Install Apache2
  apt:
    name: apache2
    state: present

- name: Start Apache2 service
  service:
    name: apache2
    state: started
    enabled: true

- name: Remove default Apache2 index.html
  file:
    path: /var/www/html/index.html
    state: absent

- name: Change site
  template:
    src: "index.html.j2"
    dest: "/var/www/html/index.html"
  notify:
    - Restart Apache2