--- #not working for some resoan
- name: Install vsftpd package
  apt:
    name: vsftpd
    state: present

- name: Create web-group
  group:
    name: webmaster
    state: present

- name: Create FTP user webmaster
  user:
    name: webmaster
    password: "{{ password | string | password_hash('sha512') }}"
    create_home: yes
    home: /var/www/html
    shell: /sbin/nologin
    system: yes
    group: webmaster
    state: present
  vars:
    password: Passw0rd!

- name: copy ftp.crt
  copy:
    src: "/etc/ssl/certs/ftp.crt"
    dest: "/etc/ssl/certs/"

- name: copy ftp.key
  copy:
    src: "/etc/ssl/private/ftp.key"
    dest: "/etc/ssl/private/"
- name: copy ca.crt
  copy:
    src: "/etc/ssl/certs/ca.crt"
    dest: "/etc/ssl/certs/"

- name: Remove default vsftpd.conf
  file:
    path: /etc/vsftpd.conf
    state: absent

- name: put the vsftpd.conf
  template:
    src: "vsftpd.conf.j2"
    dest: "/etc/vsftpd.conf"

- name: Set ownership of /var/www/html
  file:
    path: /var/www/html
    owner: webmaster
    group: webmaster
    state: directory
    recurse: yes

- name: Ensure vsftpd.chroot_list file exists
  file:
    path: /etc/vsftpd.chroot_list
    state: touch

- name: Add webmaster user to vsftpd.chroot_list
  lineinfile:
    path: /etc/vsftpd.chroot_list
    line: "webmaster"

- name: Restart vsftpd service
  service:
    name: vsftpd
    state: restarted