global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    bind *:443 ssl crt /etc/haproxy/  # Path to your SSL certificate files
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server server1 10.20.23.130:443 check
    # server server2 <web_server_2_ip>:443 check
    # Add more servers as needed